### ISSUE TITLE
Remove mc and integration tests

### ISSUE THREAD

**Issue by arschles** [deis/minio#101]
Part of https://github.com/deis/minio/issues/1 prescribed the following requirements:

Requirement 1:

```
Create a Minio MC pod to be used for testing Minio from within a Kubernetes cluster (#19)
```

Requirement 2:

```
Write an entry point on the MC pod that will run integration tests against the Minio RC to verify that it is up, running, and correctly configured. (#19)
```

These two requirements led to the creation of a `mc` directory and an `integration` directory under it. The direct contents of the `mc` directory are intended to build the [`mc`](https://github.com/minio/mc) CLI, and then the `mc/integration` directory is meant to package that CLI and an integration test (implemented as a bash script) into an image. The idea behind the integration testing image was to allow anyone to run it in a pod so it can run some basic CRUD operations against a running minio server to see if it's properly set up and running (i.e. ensure it's configured with the credentials that are stored in the object storage creds secret, it's running, its filesystem is properly set up, etc...)

We've since created [e2e tests](https://github.com/deis/workflow-e2e) which have exceeded the functionality of these tests, we haven't automated these integration tests, and we don't automatically create the integration test image.

This proposal issue is for removing the `mc` directory entirely, which would hence remove the build scripts for the `mc` CLI and the Dockerfile and image creation targets for integration tests.

Of course, if we do decide to pursue integration tests in the future (another larger discussion), we can revive the integration test script and image creation logic (and we'll need to automate test runs).

This issue would obviate #99

**Comment by mboersma** [comment]
While local integration tests would obviously be great, Workflow does effectively have test coverage of deis/minio thanks to the e2e test suite. Improving test coverage and quality is still the overall focus, but in this area the current priority is covering S3 and GCS storage instead.

I think it's safe here to simplify and remove the `mc` directory. 👍
