### ISSUE TITLE
Minio pod not starting

### ISSUE THREAD

**Issue by bscott** [deis/minio#103]
Fatal error  open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

**Comment by kmala** [comment]
which release of [workflow](https://github.com/deis/workflow) are you using?

**Comment by bscott** [comment]
@kmala 

I used Helm.
`helmc install workflow-beta4`
`# Workflow 2.0.0-beta`

**Comment by kmala** [comment]
thats pretty old release and a lot has changed drom then.....can you try the latest release 2.0.0-beta4 https://github.com/deis/workflow/blob/master/src/installing-workflow/index.md

**Comment by bscott** [comment]
@kmala I did

`helmc install workflow-beta4`

**Comment by bacongobbler** [comment]
@bscott did you run `helmc generate -x manifests workflow-beta4` before installing?

**Comment by bscott** [comment]
@bacongobbler Yes

This could be a bug in Kubernetes in Rancher, I'm going to try on a native Kubernetes cluster. I suspect that Rancher isn't handling the Kubernetes secrets well, in which Minio needs access too to start properly.

**Comment by arschles** [comment]
@bscott not sure if this is helpful, but that secret is for the default [service account](http://kubernetes.io/docs/user-guide/service-accounts/), in case that helps with your investigation into the Racher Kubernetes cluster

**Comment by bscott** [comment]
@arschles Thanks, is the secrect in the workflow repo

**Comment by bscott** [comment]
It's the objectstore secret correct?

```
➜  ~ kubectl get secrets --namespace=deis
NAME                       TYPE      DATA      AGE
builder-key-auth           Opaque    1         38m
builder-ssh-private-keys   Opaque    3         38m
database-creds             Opaque    2         38m
deis-router-dhparam        Opaque    1         38m
django-secret-key          Opaque    1         38m
objectstorage-keyfile      Opaque    2         38m
```

**Comment by kmala** [comment]
you should have a secret of type `kubernetes.io/service-account-token` something like deis-minio-token-xd86n which get created when you create a service account.
what do you get when you do `kubectl get serviceaccount --namespace=deis`

**Comment by crackmac** [comment]
I'm working with Brian and this is the output from `kubectl get serviceaccount --namespace=deis`

```
> kubectl get serviceaccount --namespace=deis
NAME                    SECRETS   AGE
default                 0         16m
deis-builder            0         16m
deis-controller         0         16m
deis-database           0         16m
deis-logger             0         16m
deis-logger-fluentd     0         16m
deis-minio              0         16m
deis-monitor-telegraf   0         16m
deis-registry           0         16m
deis-router             0         16m
deis-workflow-manager   0         16m
```

**Comment by kmala** [comment]
there is an issue in kubernetes(https://github.com/kubernetes/kubernetes/issues/25416) where secrets may not be created some time with the service account but this is not consistently reproduced.
Also can you do a `kubectl get serviceaccount` which gives you the default service account created by the kubernetes during cluster creation which gets copied to different namespaces when they are created.If even that shows 0 secrets then there was some issue with the creation of the cluster and this might be the most probable  reason https://github.com/kubernetes/kubernetes/issues/19980#issuecomment-173961597

**Comment by mboersma** [comment]
This hasn't been updated in over three months and should be fixed in current k8s / workflow.
