### ISSUE TITLE
build minio server elsewhere

### ISSUE THREAD

**Issue by arschles** [deis/minio#18]
it's currently built inside a `docker build` (https://github.com/deis/minio/blob/master/Dockerfile) and then `docker cp`-ed to the right place. it makes more sense to do the build inside a `docker run`

**Comment by bacongobbler** [comment]
shouldn't be too hard to implement if you mount the local dir :)

```
docker run -v $PWD:/go/src/github.com/deis/minio go:1.5.1 sh -c 'cd /go/src/github.com/deis/minio && make build-minio && mv /go/bin/minio /go/src/github.com/deis/minio/rootfs/bin'
```

...or something like that

**Comment by arschles** [comment]
yep :+1:
