### ISSUE TITLE
Download official minio releases on docker build

### ISSUE THREAD

**Issue by arschles** [deis/minio#30]
[This comment](https://github.com/deis/minio/issues/1#issuecomment-162118057) indicates that official releases will be ready later this month. We currently have lots of Makefile targets to build both `mc` and the server, which could go away (as could a lot of shell scripts) when we can just download releases. 

We'd also simplify the Makefile, which would mean we wouldn't have to do as much refactoring (#25).

Relates to https://github.com/deis/builder/issues/46 and https://github.com/deis/slugbuilder/issues/13.

**Comment by arschles** [comment]
@mboersma does #79 supersede this?

**Comment by mboersma** [comment]
@arschles yes, I think #79 overrides here. We still build minio from source and probably will have to until there is a new release with the multipart fix.
 Although we should keep an eye on future official minio releases--there are still some issues here for deis/registry that we hope get resolved.

**Comment by arschles** [comment]
@mboersma great, thanks
