### ISSUE TITLE
Persistent storage folder

### ISSUE THREAD

**Issue by rimusz** [deis/minio#37]
Where minio stores it's object files?
Using `/home/minio` as a docker volume minio did not start

**Comment by arschles** [comment]
Right now it stores in ephemeral storage, in the container only. I can't remember off the top of my head exactly where, but you can look at either the Dockerfile or the k8s RC manifest to find out

**Comment by rimusz** [comment]
@arschles I did not find that folder in the Dockerfile or k8s RC manifest.
I will bug you about it on Monday :)

**Comment by rimusz** [comment]
got it fixed running `sudo mkdir -p /data/deis/minio && sudo chown 1000:1000 /data/deis/minio` before installing Deis chart
