### ISSUE TITLE
question: it is optional the use of minio?

### ISSUE THREAD

**Issue by aledbf** [deis/minio#53]
In the case I want to keep using Ceph or the Ceph-less option from V1

**Comment by bacongobbler** [comment]
I know in some components (like builder) we are using the minio client to communicate with the object storage but we have open issues to change that to the AWS Go SDK so we can plug in and use any object storage like S3 or ceph. See https://github.com/deis/builder/issues/80 :)

**Comment by arschles** [comment]
@aledbf, the `mc` client that we use can communicate with many object storage systems that support the [Amazon S3 API](http://docs.aws.amazon.com/AmazonS3/latest/API/APIRest.html), so Minio is optional as long as you have an S3 compatible object store. I've only tested with Minio and S3 as of now, but I understand Ceph supports the S3 API.

Finally, to expand on @bacongobbler's comment, deis/builder#80 will enable us to expand our support for S3 compatible object stores by supporting multiple signature versions.

**Comment by arschles** [comment]
@aledbf I'm going to close this for now. Can you please re-open or file a new issue if you have further questions here?

**Comment by aledbf** [comment]
@arschles no need. I use minio just to pass the tgz between workflow and builder. I'm using a custom builder that end with a docker image not a tgz and that solves my problems. Thanks

**Comment by arschles** [comment]
Great, thanks for letting us know @aledbf
