### ISSUE TITLE
move minio config templates out, make more modular

### ISSUE THREAD

**Issue by arschles** [deis/minio#60]
- Parameterize the port and use it elsewhere (for example, in constructing the Minio client after #57)
- Put the secrets slice inside a struct, under a well known name
- Write template execution tests

**Comment by arschles** [comment]
probably more easily done after #54, since that adds go unit test support in the makefile, refactors `boot.go` and adds a `src/` directory

**Comment by technosophos** [comment]
I'm moving this out of beta1 because it doesn't seem to be necessary.

**Comment by bacongobbler** [comment]
nobody has really wanted/uses this feature so I'm going to close this for now, but let's re-open if there's a solid use case for this feature.
