### ISSUE TITLE
Try out the official release

### ISSUE THREAD

**Issue by arschles** [deis/minio#70]
It'd be great to not have to build from HEAD on every release. The official release is at: https://github.com/minio/minio/releases/tag/OFFICIAL.2016-02-08T00-12-28Z

Original discussion: https://github.com/minio/minio/issues/1041#issuecomment-181150020

**Comment by technosophos** [comment]
I'm pulling this off of the Beta milestone simply because it says "Try out" in the title. :wink:

**Comment by arschles** [comment]
@mboersma is this superseded by #79?

**Comment by mboersma** [comment]
> superceded by #79?

Yes indeed.
