### ISSUE TITLE
use the latest official minio release

### ISSUE THREAD

**Issue by arschles** [deis/minio#87]
Ref https://github.com/minio/minio/issues/1041

**Comment by bacongobbler** [comment]
Sounds like we [do so already](https://github.com/deis/minio/blob/master/rootfs/Dockerfile#L8). Is this good to close?

**Comment by mboersma** [comment]
That's just the `mc` client binary (and it's not up-to-date). The real server code gets fetched [here](https://github.com/deis/minio/blob/master/server/install.sh#L17), and it's still stuck on a specific SHA.

I think we have tried to update to current official minio releases before but found problems that made us revert. It would be worth investigating again.

**Comment by arschles** [comment]
Moving this out of RC1, as we'll want to vet this change well before merging. I'd rather not introduce so much velocity this close to the RC1 release date.

**Comment by arschles** [comment]
Closed by #106
