### ISSUE TITLE
Add documentation in the README about limiting disk space

### ISSUE THREAD

**Issue by arschles** [deis/minio#88]
There is a [design doc](https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/design/resources.md) for adding a disk space resource, but it's not implemented yet. When it is, add a note in the README for how to limit disk space.

**Comment by arschles** [comment]
This issue was created in response to https://github.com/deis/workflow/pull/91#issuecomment-197970572

**Comment by bacongobbler** [comment]
this still hasn't been implemented as of k8s 1.4, FYI. Perhaps in a 2.0?

**Comment by bacongobbler** [comment]
still not implemented as of k8s 1.5. I'm going to close this; let's re-open when storage limitations are available.
